package A2;

public class accountant extends employee {

    accountant(String inNIC, String inName, int inNumber, String inEmail, String inEmpID, double inSal, String inDept) {
        super(inNIC, inName, inNumber, inEmail, inEmpID, inSal, inDept);
    }

    void generateTicketsIssued(station inStation)
    {
        System.out.println("Station "+inStation.stationName+" has issued "+inStation.inCount+" tickets");
    }

    void generateTicketsArrived(station outStation)
    {
        System.out.println("Station "+outStation.stationName+" has "+outStation.outCount+" departures");
    }

    void totalTripsPerCommuter(user inUser)
    {
        System.out.println(inUser.name+" has had "+inUser.tickets+" trips");
    }

    void incomeRailway(railway inRailway)
    {
        System.out.println("Income generated by the A2.railway "+(inRailway.getTotalIncomeTrips()-inRailway.getExpenses()));
    }
}
